SUB-3067 dotnet sonar
submittable/github-actions pull request #12
Opened 2022-01-05 11:58 UTC by jchima

2022-01-05 17:45 UTC, tevans-submittable requested changes
We cannot have any strings unique to a developer repo hard coded in our "Universal pipeline"  Convert these to parameters if there is no other solution like wildcarding the search strings

2022-01-05 17:45 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "project.csproj"
Dose this action accept a file name like  *.csproj?

2022-01-05 17:45 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "Submittable.Serverless.sln"
Have this specific solution file name here breaks the universality of this pipeline.  Same for the below action calls

2022-01-05 17:45 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "package.json, Dockerfile, next.config.js"
Why is a Dockerfile indicative of a nodejs project?  Do we need a separate action to test for repos use of Docker in isolation?

2022-01-05 17:54 UTC, jchima commented on .github/workflows/ci.yml
> +          files: "project.csproj"
I added this step as a placeholder to check for .net core project, it will be replaced once we start getting into building .net core/framework projects. For now it won't do anything apart from checking if a .net project file exists

2022-01-05 17:57 UTC, jchima commented on .github/workflows/ci.yml
> +          files: "Submittable.Serverless.sln"
like we discussed yesterday, we're looking to run sonarqube scan on the repos, this one is specifically for service repo. It is a way of identifying the repo which will in turn make it easy for sonar to scan the project. I've not found a unified approach for our .Net apps since they're built differently, hence why I'm working off of a specific file type

2022-01-05 17:59 UTC, jchima commented on .github/workflows/ci.yml
> +          files: "package.json, Dockerfile, next.config.js"
again another way to identify and build nodejs apps, since some of the .Net apps have this file living in their root dir. There is also an action that checks for Dockerfile only

2022-01-05 20:15 UTC, chrisjdewitt commented on .github/workflows/ci.yml
> +          files: "project.csproj"
Caller workflow should pass value for its equivalent of project.csharp

2022-01-05 20:17 UTC, chrisjdewitt commented on .github/workflows/ci.yml
> +          dotnetBuildArguments: ./src/Submittable.Api
This value should be parameterized.

2022-01-05 20:18 UTC, chrisjdewitt commented on .github/workflows/ci.yml
> +        if: steps.check_files_dotnet_sonar_manager_submittable_com.outputs.files_exists == 'true'
This block should be for .NET Framework generically, not specifically manager (see also admin.submittable.com).

2022-01-05 20:19 UTC, chrisjdewitt commented on .github/workflows/ci.yml
> +        run: nuget restore ./SQSListener/SQSListener/SQSListener.csproj
This value should be parameterized.

2022-01-05 20:19 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "package.json, Dockerfile, next.config.js"
Is the opposite correct as well, Every directory that has a Dockerfile will be a node project?  I dont think that is a good file for to use for this condition

2022-01-05 20:21 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "Source/Submittable.Api"
This should not be project specific, Can this be something like **/*.csproj  ?

2022-01-05 20:25 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +      - name: Check file existence for .Net manager.submittable.com Project
No action in this universal workflow should be specific to an individual project/repo

2022-01-05 20:26 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +        run: nuget restore ./SQSListener/SQSListener/SQSListener.csproj
This action should be able to run a restore on any dotnet projects

2022-01-06 20:29 UTC, tevans-submittable reviewed
Big step in the right direction, had a few comments

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +        default: 'src/Submittable.Api'
I dont think this is an appropriate default value for a universal pipeline

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +        description: 'sets .net version'
Can we be explicit that this is dotnet core in the description

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +        run: nuget restore ./${{ inputs.file_check_path_dotnet }}
This command is redundant with the "dotnet restore" call

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
The test fiile check values are never used beyond the boolean check.  If we dont need to re-use the string value during the actual test command these inputs can be booleans

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "${{ inputs.file_check_path_python }}"
Should this value be used below in the python dependency install?

2022-01-06 20:29 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          dotnetDisableTests: true
Should this be bound to your test check variable?

2022-01-11 12:39 UTC, jchima commented on .github/workflows/ci.yml
> +          files: "${{ inputs.file_check_path_python }}"
this is just a placeholder to build python code if requirements.txt or any other python related file is available in the root folder

2022-01-11 12:40 UTC, jchima commented on .github/workflows/ci.yml
> +          dotnetDisableTests: true
this is for sonarqube build and scan, different from the test file checker which run unit tests if the test files are present

2022-01-11 12:43 UTC, jchima commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
They are used in this block if: steps.check_files_nodejs_test.outputs.files_exists == 'true' from line 139 to 143

2022-01-11 12:46 UTC, jchima commented on .github/workflows/ci.yml
> +        run: nuget restore ./${{ inputs.file_check_path_dotnet }}
I updated this line with dotnet restore command

2022-01-11 12:46 UTC, jchima commented on .github/workflows/ci.yml
> +        description: 'sets .net version'
updated

2022-01-11 12:48 UTC, jchima commented on .github/workflows/ci.yml
> +        default: 'src/Submittable.Api'
this is just a place holder that could be changed. Do you have any recommendations?

2022-01-11 15:58 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +        default: 'src/Submittable.Api'
Whats in their documentation is more generic 'src/' but I think no default is just as acceptable

2022-01-11 16:01 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
That is what I meant by a boolean check.  If that is the only usage this can be simplified by using a boolean input.  Or should it be used somewhere in the Run Nodejs tests?

2022-01-11 16:05 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "${{ inputs.file_check_path_python }}"
Why does it have to be the root folder?  If an inpiut of "./foobar/requirements.txt" is provided the "Install Python Dependencies" step should fail as it would still expect to find the requirements in the project root?

2022-01-11 16:11 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          dotnetDisableTests: true
I believe this is instructing the action to run tests, This seems redundant as we do it in " Run .Net test with .Net CLI".  Is Sonar capable of consuming the results from that step?

2022-01-11 17:10 UTC, jchima commented on .github/workflows/ci.yml
> +          dotnetDisableTests: true
it is disabling the test "dotnetDisableTests"

2022-01-19 12:11 UTC, jchima commented on .github/workflows/ci.yml
> +        default: 'src/Submittable.Api'
Updated with no default value

2022-01-19 12:13 UTC, jchima commented on .github/workflows/ci.yml
> +          files: "${{ inputs.file_check_path_python }}"
it doesn't have to be in the root folder, it can search other paths as well.

2022-01-19 12:21 UTC, jchima commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
@tevans-submittable we do use the check test file when running the pipeline and not just to check if the files are there (line 195 - 203). Now the reason why i set it this way is so that the user can add the path to where the test files live. We cannot just use booleans as it would make it more complex

2022-01-19 12:21 UTC, jchima commented on .github/workflows/ci.yml
>            sonarProjectKey: ${{ inputs.repo_name }}
I don't see any issues with this action, it is also maintained and managed by the creator with MIT license. https://github.com/highbyte/sonarscan-dotnet

2022-01-19 14:47 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
Maybe im missing something, but what line is "file_check_path_nodejs_test" referenced on in 195-203?

2022-01-19 14:50 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +          files: "${{ inputs.file_check_path_python }}"
This is essential the same comment as with, "file_check_path_nodejs_test".  If a file is provided that is not in the root repo the "Install Python Dependencies" step will fail or build the wrong project, but we can address it when we see the failure

2022-01-19 14:50 UTC, tevans-submittable commented on .github/workflows/ci.yml
> +      file_check_path_nodejs_test:
We can address this when we encounter this edge case

2022-01-19 14:51 UTC, tevans-submittable approved these changes
Needs to merge with master, but let get this in so we can continue to add usecases

2022-01-19 20:05 UTC, merged